package org.firstinspires.ftc.teamcode; // This should match the file location. This is auto generated by Android Studio

import com.qualcomm.robotcore.eventloop.opmode.OpMode;
import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import com.pedropathing.api.PoseFactory;
import com.pedropathing.math.Pose;
import com.pedropathing.follower.Follower;
import org.firstinspires.ftc.teamcode.pedroPathing.Constants;
@Autonomous
public class Blue1_AllOneSide extends OpMode {

    @Override
    public void init() {
        Follower follower;
        final PoseFactory p = PoseFactory.degrees();
        final Pose startPos = p.of(85, 133, 270);

        follower = Constants.create(hardwareMap);

        follower.setPose(startPos);
    }

    @Override
    public void start() {

    }

    @Override
    public void loop() {

    }
}