package org.firstinspires.ftc.teamcode; // This should match the file location. This is auto generated by Android Studio

import com.qualcomm.robotcore.eventloop.opmode.OpMode;
import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import com.pedropathing.follower.Follower;
import org.firstinspires.ftc.teamcode.pedro.Constants;
import com.pedropathing.api.PoseFactory;
import com.pedropathing.math.Pose;
import static com.pedropathing.api.Paths.*;
import com.pedropathing.paths.Path;

import static com.pedropathing.ivy.Scheduler.schedule;

import com.pedropathing.ivy.Command;
import com.pedropathing.ivy.Scheduler;

import static com.pedropathing.ivy.groups.Groups.sequential;
import static com.pedropathing.ivy.pedro.PedroCommands.follow;
@Autonomous
public class Red1_AllOneSide extends OpMode {
    private Follower follower;
    private final PoseFactory p = PoseFactory.degrees(); // add this
    // our poses
    private final Pose start = p.of(60, 8, 90);
    private final Pose shootpos1 = p.of(60, 24, 90);
    private final Pose collectgarden1 = p.of(21, 8, 180);
    private final Pose collectgarden1control = p.of(57.5692, 17.2571, 0);
    private final Pose collectgarden2 = p.of(8, 8, 180);
    private final Pose shoot2control = p.of(36.7524, 20.0658, 0);
    private final Pose collectflower1 = p.of(20, 47, 180);
    private final Pose collectflower1control = p.of(59, 24, 0);
    private final Pose collectflower2 = p.of(10, 47, 180);
    private final Pose park = p.of(10, 95, 0);
    private final Pose parkControl1 = p.of(9.3549, 47.0777, 0);

    //poses from before

    private Path shoot1() {
        return line(start, shootpos1).linear(start, shootpos1);
    }
    private Path collectGarden1() {
        return curve(shootpos1, collectgarden1control, collectgarden1).linear(shootpos1, collectgarden1);
    }
    private Path collectGarden2() {
        return line(collectgarden1, collectgarden2).linear(collectgarden1, collectgarden2);
    }
    private Path shoot2() {
        return curve(collectgarden2, shoot2control, shootpos1).linear(collectgarden2, shootpos1);
    }
    private Path collectFlower1() {
        return curve(shootpos1, collectflower1control, collectflower1).linear(shootpos1, collectflower1);
    }
    private Path collectFlower2() {
        return line(collectflower1, collectflower2).linear(collectflower1, collectflower2);
    }
    private Path shoot3() {
        return line(collectflower2, shootpos1).linear(collectflower2, shootpos1);
    }
    private Path park() {
        return curve(shootpos1, parkControl1, park).linear(shootpos1, park);
    }
    private Command autoRoutine() {
        return sequential(
                follow(follower, shoot1()),
                follow(follower, collectGarden1()),
                follow(follower, collectGarden2()),
                follow(follower, shoot2()),
                follow(follower, collectFlower1()),
                follow(follower, collectFlower2()),
                follow(follower, shoot3()),
                follow(follower, park())
        );
    }

    @Override
    public void init() {
        Scheduler.reset();

        follower = Constants.create(hardwareMap);
        follower.setPose(start);
        follower.update();
    }

    @Override
    public void start() {
        schedule(autoRoutine());
    }

    @Override
    public void loop() {
        follower.update();
        Scheduler.execute();

        telemetry.addData("X", follower.pose().x());
        telemetry.addData("Y", follower.pose().y());
        telemetry.addData("Heading", Math.toDegrees(follower.pose().heading()));
        telemetry.addData("Follower Mode", follower.mode());
        telemetry.update();
    }
}