package org.firstinspires.ftc.teamcode; // This should match the file location. This is auto generated by Android Studio

import com.qualcomm.robotcore.eventloop.opmode.OpMode;
import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import com.pedropathing.follower.Follower;
import org.firstinspires.ftc.teamcode.pedro.Constants;
import com.pedropathing.api.PoseFactory;
import com.pedropathing.math.Pose;
import static com.pedropathing.api.Paths.*;
import com.pedropathing.paths.Path;

import static com.pedropathing.ivy.Scheduler.schedule;

import com.pedropathing.ivy.Command;
import com.pedropathing.ivy.Scheduler;

import static com.pedropathing.ivy.groups.Groups.sequential;
import static com.pedropathing.ivy.pedro.PedroCommands.follow;
@Autonomous
public class Red2_AllOneSide extends OpMode {
    private Follower follower;
    private final PoseFactory p = PoseFactory.degrees(); // add this
    // our poses
    private final Pose start = p.of(60, 133, 90);
    private final Pose shootpos1 = p.of(60, 118, 270);
    private final Pose collectflower1 = p.of(47, 125, 90);
    private final Pose collectflower1control1 = p.of(50.3566, 120.0518, 0);
    private final Pose collectflower2 = p.of(47, 133, 90);
    private final Pose shoot2part1 = p.of(47, 125, 90);
    private final Pose shoot2part2 = p.of(60, 118, 270);
    private final Pose shoot2part2control1 = p.of(50.3195, 119.5682, 0);
    private final Pose park = p.of(10, 118, 0);

    private Path shoot1() {
        return line(start, shootpos1).linear(start, shootpos1);
    }
    private Path collectflower1() {
        return curve(shootpos1, collectflower1control1, collectflower1).linear(shootpos1, collectflower1);
    }
    private Path collectflower2() {
        return line(collectflower1, collectflower2).linear(collectflower1, collectflower2);
    }
    private Path shoot2part1() {
        return line(collectflower2, shoot2part1).linear(collectflower2, shoot2part1);
    }
    private Path shoot2part2() {
        return curve(shoot2part1, shoot2part2control1, shoot2part2).linear(shoot2part1, shoot2part2);
    }
    private Path park() {
        return line(shoot2part2, park).linear(shoot2part2, park);
    }
    private Command autoRoutine() {
        return sequential(
                follow(follower, shoot1()),
                follow(follower, collectflower1()),
                follow(follower, collectflower2()),
                follow(follower, shoot2part1()),
                follow(follower, shoot2part2()),
                follow(follower, park())
        );
    }

    @Override
    public void init() {
        Scheduler.reset();

        follower = Constants.create(hardwareMap);
        follower.setPose(start);
        follower.update();
    }

    @Override
    public void start() {
        schedule(autoRoutine());
    }

    @Override
    public void loop() {
        follower.update();
        Scheduler.execute();

        telemetry.addData("X", follower.pose().x());
        telemetry.addData("Y", follower.pose().y());
        telemetry.addData("Heading", Math.toDegrees(follower.pose().heading()));
        telemetry.addData("Follower Mode", follower.mode());
        telemetry.update();
    }
}