package org.firstinspires.ftc.teamcode; // This should match the file location. This is auto generated by Android Studio

import com.qualcomm.robotcore.eventloop.opmode.OpMode;
import com.qualcomm.robotcore.eventloop.opmode.Autonomous;
import com.pedropathing.api.PoseFactory;
import com.pedropathing.math.Pose;
import com.pedropathing.follower.Follower;
import org.firstinspires.ftc.teamcode.pedro.Constants;
import static com.pedropathing.api.Paths.*;
import com.pedropathing.paths.Path;
@Autonomous
public class TestAutonomous extends OpMode {

    @Override
    public void init() {

        Follower follower;
        final PoseFactory p = PoseFactory.degrees();
        final Pose startPose = p.of(24, 24, 0);
        final Pose park = p.of(48, 48, 90);
        final Pose controlPose = p.of(36, 60, 45);

        follower = Constants.create(hardwareMap);

        follower.setPose(startPose);
    }

    @Override
    public void start() {

    }

    @Override
    public void loop() {

    }
}